
let allChamp = [
  { name : 'Taric',
 img: 'https://memehay.com/meme/20211201/la-ai-ai-muon-mac-ket-trong-lau-dai-tinh-ai.jpg',
 img_lock: 'https://media.techz.vn/resize_x450x260/media2019/upload2019/2020/09/08/Dam-vinh-hung-vua-tiet-lo-ly-do-chia-tay-nguoi-yeu-cu-dan-mang-dong-long-ung-ho-6_08092020094302.jpg',
 vitri : 'sp',
 skins : [ {name: "Trang phục mặc định",video : 'videos/taric/skin_mac_dinh.mp4'} ,
 {name: "Taric giọt lệ sầu bi ",video : 'videos/taric/skin1.mp4'},
 {name: "Taric bán xà bông ",video : 'videos/taric/skin2.mp4'},]
},
{ name : 'Akali',
 img: 'https://vnn-imgs-f.vgcloud.vn/2021/10/03/20/cong-an-tp-hcm-yeu-cau-cung-cap-thong-tin-nghe-si-lam-tu-thien-theo-phan-anh-cua-ba-nguyen-phuong-hang.jpeg',
 img_lock : 'https://tintucnong24gio.com/wp-content/uploads/2021/05/ho.png?v=1620436518',
 vitri :'mid',
 skins : [ {name: "Trang phục mặc định",video : 'videos/akali/skin_mac_dinh.mp4'},
 {name: "Akali VS Taric",video : 'videos/akali/skin1.mp4'}]
},
{ name : 'Rengar',
 img: 'https://memehay.com/files/posts/20201110/tran-duc-bo-noi-hummmmmm.jpg',
 img_lock : 'https://i.pinimg.com/originals/1c/f6/e3/1cf6e315ad8fa42d9b5df247c5c6e9ec.jpg',
 vitri : 'rung',
 skins : [ {name: "Trang phục mặc định",video : 'videos/rengar/tdb.mp4'},
 {name: "Rengar báo đốm",video : 'videos/rengar/skin1.mp4'},
 {name: "Rengar Ka Xỷ Pí Ẳng",video : 'videos/rengar/skin2.mp4'}]
},
{ name : 'Varus',
 img: 'https://35express.org/wp-content/uploads/2021/12/tiktoker-huynh-dat-la-ai-1-35express.jpg',
 img_lock : 'https://i.ytimg.com/vi/mJpJhVTxtN0/maxresdefault.jpg',
 vitri: 'ad',
 skins : [ {name: "Trang phục mặc định",video : 'videos/varus/huynhdatdibodoi.mp4'},
 {name: "Varus tức nước trong quần",video : 'videos/varus/skin1.mp4'},
 {name: "Varus mũi tên tình ái ",video : 'videos/varus/skin2.mp4'}]
},
{ name : 'Lucian',
 img: 'https://scontent.fdad1-2.fna.fbcdn.net/v/t1.15752-9/259013112_1029798464241592_5817412410378623840_n.png?_nc_cat=105&ccb=1-5&_nc_sid=ae9488&_nc_ohc=QY5iNXvAXPUAX-CWF6D&_nc_ht=scontent.fdad1-2.fna&oh=03_AVJE-P3ollrRg93Rdjo5LHX5DlnMUdUl83gdJOs_IdtsHw&oe=622E615A',
 img_lock : 'https://scontent.fdad2-1.fna.fbcdn.net/v/t1.15752-9/272769093_311622417607083_3229862593122051665_n.png?_nc_cat=101&ccb=1-5&_nc_sid=ae9488&_nc_ohc=Wslb1O8I8BsAX8IsWBt&_nc_ht=scontent.fdad2-1.fna&oh=03_AVIYaFJwJ2VPtTIkRYp8JC0rFfrokxKKVYML3X4z8oa0iA&oe=622EE3FC',
 vitri : 'ad',
 skins : [ {name: "Trang phục mặc định",video : 'videos/lucian/skin_mac_dinh.mp4'},
 {name: "Lucian chửi banh háng",video : 'videos/lucian/skin1.mp4'},
 {name: "Lucian khóc tiếng mán ",video : 'videos/lucian/skin2.mp4'},]
},
{ name : 'Yummi',
 img: 'https://tinhhoabacbo.com/wp-content/uploads/2021/12/m10.jpg',
 img_lock : 'https://kenh14cdn.com/thumb_w/660/203336854389633024/2021/4/17/photo-1-1618644236003344274535.jpg',
 vitri : 'sp',
 skins : [ {name: "Trang phục mặc định",video : 'videos/yummi/meosimy.mp4'},]
},
{ name : 'Caitlyn',
 img: 'https://gamek.mediacdn.vn/133514250583805952/2021/10/18/base64-1634526438582612507716.png',
 img_lock : 'https://i.ytimg.com/vi/j8mZDd9sVYw/maxresdefault.jpg',
 vitri : 'ad',
 skins : [ {name: "Trang phục mặc định",video : 'videos/catily/congan.mp4'},
 {name: "Rapper Caitlyn",video : 'videos/catily/skin1.mp4'},
 {name: "Caitlyn  sin lõy",video : 'videos/catily/skin2.mp4'},]
},
{ name : 'Zac',
img: 'images/quangdragon.jpg',
img_lock : 'images/quangdragon.jpg',
skins : [ {name: "Trang phục mặc định",video : 'videos/zac/skin_mac_dinh.mp4'},
 {name: "Zac: chàng phù thủy chổng háng",video : 'videos/zac/skin1.mp4'},
 {name: "Zac lạnh lùng boiz",video : 'videos/zac/skin2.mp4'},
 {name: "Zac Alime",video : 'videos/zac/skin3.mp4'},]
},
/*
{ name : 'Darius',
 img: 'images/thaybadit.jpg',
 video :'videos/thaybadit.mp4',
 img_lock : 'images/thaybadit.jpg',
},
{ name : 'Yasuo',
 img: 'images/lancoolngau.jpg',
 video :'videos/chuatebia.mp4',
 img_lock : 'images/lancoolngau.jpg',
},{ name : 'Jayce',
img: 'images/chuatemuaquat.jpg',
video :'videos/chuatemuaquat.mp4',
img_lock : 'images/chuatemuaquat.jpg',
},{ name : 'Garen',
img: 'images/anhbana.jpg',
video :'videos/anhbana.mp4',
img_lock : 'images/anhbana.jpg',
},
{ name : 'Xinzhao',
img: 'images/mcviethoang.jpg',
video :'videos/mcviethoang.mp4',
img_lock : 'images/mcviethoang.jpg',
},{ name : 'Vi',
img: 'images/linda.jpg',
video :'videos/linda.mp4',
img_lock : 'images/linda.jpg',
},
{ name : 'Ekko',
img: 'images/coancohoc.jpg',
video :'videos/coancohoc.mp4',
img_lock : 'images/coancohoc.jpg',
},{ name : 'Shaco',
img: 'images/chemchetmaychu.jpg',
video :'videos/ongtrumyoyo.mp4',
img_lock : 'images/khocloc.jpg',
},
{ name : 'Braum',
img: 'images/dongchikhoa.jpg',
video :'videos/thanhso.mp4',
img_lock : 'images/dongchikhoa.jpg',
},{ name : 'Vayne',
img: 'images/tungson.jpg',
video :'videos/tungson.mp4',
img_lock : 'images/tungson.jpg',
},
{ name : 'Soroka',
img: 'images/trungnung.jpg',
video :'videos/trungnung.mp4',
img_lock : 'images/trungnung.jpg',
},
{ name : 'Zilean',
img: 'images/thayongnoi.jpg',
video :'videos/thayongnoi.mp4',
img_lock : 'images/thayongnoi.jpg',
},
{ name : 'Ryze',
img: 'https://th.bing.com/th/id/R.e5fff8b7bb9cf29bcd2071a71be2d1a6?rik=jFTutam4r8wrrw&pid=ImgRaw&r=0',
video :'videos/trandan.mp4',
img_lock : 'https://th.bing.com/th/id/OIP.GCrV45vza0YJHBqnyZAo9wHaHa?pid=ImgDet&rs=1',
},
{ name : 'Nunu & Willump',
img: 'images/yanghomang.jpg',
video :'videos/yanghomang.mp4',
img_lock : 'images/yanghomang.jpg',
},

{ name : 'Fiora',
img: 'images/nhuchanhcho.jpg',
video :'videos/nhuchanhcho.mp4',
img_lock : 'images/nhuchanhcho.jpg',
},
{ name : 'Riven',
img: 'images/dieuhien.jpg',
video :'videos/dieuhien.mp4',
img_lock : 'images/dieuhien.jpg',
},
{ name : 'Tristana',
img: 'images/cuoi.jpg',
video :'videos/cuoi.mp4',
img_lock : 'images/cuoi.jpg',
},
{ name : 'Jax',
img: 'https://th.bing.com/th/id/OIP.anqaA9JFaDapnAChG4qaQgHaHa?w=182&h=182&c=7&r=0&o=5&dpr=1.12&pid=1.7',
video :'videos/khab.mp4',
img_lock : 'https://th.bing.com/th/id/OIP.3-Bzk9YyUSFCPGQgkt4A2QHaEK?w=309&h=180&c=7&r=0&o=5&dpr=1.12&pid=1.7',
},
{ name : 'Swain',
img: 'images/rapviet.jpg',
video :'videos/rapviet.mp4',
img_lock : 'images/rapviet.jpg',
},
{ name : 'Sett',
img: 'https://th.bing.com/th/id/OIP.XChDwbdeinQWcutAPcBIiAHaGQ?w=227&h=191&c=7&r=0&o=5&dpr=1.12&pid=1.7',
video :'videos/jonnydang.mp4',
img_lock : 'https://th.bing.com/th/id/OIP.K9gt5TrGq1bgaMLpL3sSgQHaE2?w=291&h=191&c=7&r=0&o=5&dpr=1.12&pid=1.7',
},
{ name : 'Udyr',
img: 'https://th.bing.com/th/id/OIP.9lB_dZxKnJUEOMmFM-oAvQHaEK?w=304&h=180&c=7&r=0&o=5&dpr=1.12&pid=1.7',
video :'videos/khoapug.mp4',
img_lock : 'https://th.bing.com/th/id/OIP.EN0GE0_CIK5xYJbCjXBObQHaEG?w=297&h=180&c=7&r=0&o=5&dpr=1.12&pid=1.7',
},*/
];